name: Angular

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install angular
      run:  npm install -g @angular/cli
    - name: npm install
      run:  npm install --save
    - name: angular build
      run: ng build --prod
    - name: publish
      run: git config --global user.email "karthik1705.n@gmail.com" && git config --global user.name "Karthik Nedunchezhiyan" && git add . && git commit -m "dist update" && git push origin `git subtree split --prefix dist/splitbill main`:gh-pages --force
